/*
    BasicClassTemplate.cpp
    

*/
//----------------------------------------
//BasicClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:55:54 PM
//----------------------------------------
#include "BasicClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


BasicClassTemplate::BasicClassTemplate()
{

}

void BasicClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{

}

CodeTemplateType BasicClassTemplate::getType() const
{
    return CodeTemplateType::BasicClass;
}

BasicClassTemplate::~BasicClassTemplate()
{

}




}}}}//end namespace


