/*
    CBGameClassTemplate.cpp
    

*/
//----------------------------------------
//CBGameClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:58:41 PM
//----------------------------------------
#include "CBGameClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


CBGameClassTemplate::CBGameClassTemplate()
{

}

void CBGameClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{

}

CodeTemplateType CBGameClassTemplate::getType() const
{
    return CodeTemplateType::CBGameClass;
}

CBGameClassTemplate::~CBGameClassTemplate()
{

}




}}}}//end namespace


