/*
    CBGameEntryPointTemplate.cpp
    

*/
//----------------------------------------
//CBGameEntryPointTemplate.cpp generated by cbtek on 06-06-2017 at 01:00:16 PM
//----------------------------------------
#include "CBGameEntryPointTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


CBGameEntryPointTemplate::CBGameEntryPointTemplate()
{

}

void CBGameEntryPointTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{

}

CodeTemplateType CBGameEntryPointTemplate::getType() const
{
    return CodeTemplateType::CBGameEntryPoint;
}

CBGameEntryPointTemplate::~CBGameEntryPointTemplate()
{

}




}}}}//end namespace


