/*
    CodeTemplateClassTemplate.cpp
    

*/
//----------------------------------------
//CodeTemplateClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:59:01 PM
//----------------------------------------
#include "CodeTemplateClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


CodeTemplateClassTemplate::CodeTemplateClassTemplate()
{

}

void CodeTemplateClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{

}

CodeTemplateType CodeTemplateClassTemplate::getType() const
{
    return CodeTemplateType::CodeTemplateClass;
}

CodeTemplateClassTemplate::~CodeTemplateClassTemplate()
{

}




}}}}//end namespace


