/*
    CodeGenCodeTemplateClassTemplate.cpp
    

*/
//----------------------------------------
//CodeGenCodeTemplateClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:59:01 PM
//----------------------------------------
#include "CodeGenCodeTemplateClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


CodeGenCodeTemplateClassTemplate::CodeGenCodeTemplateClassTemplate()
{

}

void CodeGenCodeTemplateClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{
    THROW_GENERIC_EXCEPTION("Not Implemented");
}

CodeTemplateType CodeGenCodeTemplateClassTemplate::getType() const
{
    return CodeTemplateType::CodeGenCodeTemplateClass;
}

CodeGenCodeTemplateClassTemplate::~CodeGenCodeTemplateClassTemplate()
{

}




}}}}//end namespace


