/*
    CodeGenProjectTemplateClassTemplate.cpp
    

*/
//----------------------------------------
//CodeGenProjectTemplateClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:59:06 PM
//----------------------------------------
#include "CodeGenProjectTemplateClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


CodeGenProjectTemplateClassTemplate::CodeGenProjectTemplateClassTemplate()
{

}

void CodeGenProjectTemplateClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{
    THROW_GENERIC_EXCEPTION("Not Implemented");
}

CodeTemplateType CodeGenProjectTemplateClassTemplate::getType() const
{
    return CodeTemplateType::CodeGenProjectTemplateClass;
}

CodeGenProjectTemplateClassTemplate::~CodeGenProjectTemplateClassTemplate()
{

}




}}}}//end namespace


