/*
    EnumClassTemplate.cpp
    

*/
//----------------------------------------
//EnumClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:56:44 PM
//----------------------------------------
#include "EnumClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


EnumClassTemplate::EnumClassTemplate()
{

}

void EnumClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{

}

CodeTemplateType EnumClassTemplate::getType() const
{
    return CodeTemplateType::EnumClass;
}

EnumClassTemplate::~EnumClassTemplate()
{

}




}}}}//end namespace


