/*
    MainEntryPointTemplate.cpp
    

*/
//----------------------------------------
//MainEntryPointTemplate.cpp generated by cbtek on 06-06-2017 at 12:59:53 PM
//----------------------------------------
#include "MainEntryPointTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


MainEntryPointTemplate::MainEntryPointTemplate()
{

}

void MainEntryPointTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{

}

CodeTemplateType MainEntryPointTemplate::getType() const
{
    return CodeTemplateType::MainEntryPoint;
}

MainEntryPointTemplate::~MainEntryPointTemplate()
{

}




}}}}//end namespace


