/*
    ProjectTemplateClassTemplate.cpp
    

*/
//----------------------------------------
//ProjectTemplateClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:59:06 PM
//----------------------------------------
#include "ProjectTemplateClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


ProjectTemplateClassTemplate::ProjectTemplateClassTemplate()
{

}

void ProjectTemplateClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{

}

CodeTemplateType ProjectTemplateClassTemplate::getType() const
{
    return CodeTemplateType::ProjectTemplateClass;
}

ProjectTemplateClassTemplate::~ProjectTemplateClassTemplate()
{

}




}}}}//end namespace


