/*
    QDialogClassTemplate.cpp
    

*/
//----------------------------------------
//QDialogClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:59:27 PM
//----------------------------------------
#include "QDialogClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


QDialogClassTemplate::QDialogClassTemplate()
{

}

void QDialogClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{
    THROW_GENERIC_EXCEPTION("Not Implemented");
}

CodeTemplateType QDialogClassTemplate::getType() const
{

}

QDialogClassTemplate::~QDialogClassTemplate()
{

}




}}}}//end namespace


