/*
    QMainWindowClassTemplate.cpp
    

*/
//----------------------------------------
//QMainWindowClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:59:19 PM
//----------------------------------------
#include "QMainWindowClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


QMainWindowClassTemplate::QMainWindowClassTemplate()
{

}

void QMainWindowClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{

}

CodeTemplateType QMainWindowClassTemplate::getType() const
{
    return CodeTemplateType::QMainWindowClass;
}

QMainWindowClassTemplate::~QMainWindowClassTemplate()
{

}




}}}}//end namespace


