/*
    QtMainEntryPoint.cpp
    

*/
//----------------------------------------
//QtMainEntryPoint.cpp generated by cbtek on 06-06-2017 at 01:00:24 PM
//----------------------------------------
#include "QtMainEntryPoint.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


QtMainEntryPoint::QtMainEntryPoint()
{

}

void QtMainEntryPoint::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{

}

CodeTemplateType QtMainEntryPoint::getType() const
{
    return CodeTemplateType::QtMainEntryPoint;
}

QtMainEntryPoint::~QtMainEntryPoint()
{

}




}}}}//end namespace


