/*
    QWidgetClassTemplate.cpp
    

*/
//----------------------------------------
//QWidgetClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:59:34 PM
//----------------------------------------
#include "QWidgetClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


QWidgetClassTemplate::QWidgetClassTemplate()
{

}

void QWidgetClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{
    THROW_GENERIC_EXCEPTION("Not Implemented");
}

CodeTemplateType QWidgetClassTemplate::getType() const
{
    return CodeTemplateType::QWidgetClass;
}

QWidgetClassTemplate::~QWidgetClassTemplate()
{

}




}}}}//end namespace


