/*
    RStatsModuleUIClassTemplate.cpp
    

*/
//----------------------------------------
//RStatsModuleUIClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:57:35 PM
//----------------------------------------
#include "RStatsModuleUIClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


RStatsModuleUIClassTemplate::RStatsModuleUIClassTemplate()
{

}

void RStatsModuleUIClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{

}

CodeTemplateType RStatsModuleUIClassTemplate::getType() const
{
    return CodeTemplateType::RStatsModuleUIClass;
}

RStatsModuleUIClassTemplate::~RStatsModuleUIClassTemplate()
{

}




}}}}//end namespace


