/*
    SingletonClassTemplate.cpp
    

*/
//----------------------------------------
//SingletonClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:56:20 PM
//----------------------------------------
#include "SingletonClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


SingletonClassTemplate::SingletonClassTemplate()
{

}

void SingletonClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{
    THROW_GENERIC_EXCEPTION("Not Implemented");
}

CodeTemplateType SingletonClassTemplate::getType() const
{

}

SingletonClassTemplate::~SingletonClassTemplate()
{

}




}}}}//end namespace


