/*
    StaticClassTemplate.cpp
    

*/
//----------------------------------------
//StaticClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:56:28 PM
//----------------------------------------
#include "StaticClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


StaticClassTemplate::StaticClassTemplate()
{

}

void StaticClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{
    THROW_GENERIC_EXCEPTION("Not Implemented");
}

CodeTemplateType StaticClassTemplate::getType() const
{
    return CodeTemplateType::StaticClass;
}

StaticClassTemplate::~StaticClassTemplate()
{

}




}}}}//end namespace


