/*
    TemplateClassTemplate.cpp
    

*/
//----------------------------------------
//TemplateClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:56:36 PM
//----------------------------------------
#include "TemplateClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


TemplateClassTemplate::TemplateClassTemplate()
{

}

void TemplateClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{
    THROW_GENERIC_EXCEPTION("Not Implemented");
}

CodeTemplateType TemplateClassTemplate::getType() const
{
    return CodeTemplateType::TemplateClass;
}

TemplateClassTemplate::~TemplateClassTemplate()
{

}




}}}}//end namespace


