/*
    VirtualClassTemplate.cpp
    

*/
//----------------------------------------
//VirtualClassTemplate.cpp generated by cbtek on 06-06-2017 at 12:56:13 PM
//----------------------------------------
#include "VirtualClassTemplate.h"

namespace cbtek {
namespace products {
namespace codegen {
namespace code_templates {


VirtualClassTemplate::VirtualClassTemplate()
{

}

void VirtualClassTemplate::createCode(const std::string &name, const std::string &rootFolderIncPath, const std::string &rootFolderSrcPath)
{
    THROW_GENERIC_EXCEPTION("Not Implemented");
}

CodeTemplateType VirtualClassTemplate::getType() const
{
    return CodeTemplateType::VirtualClass;
}

VirtualClassTemplate::~VirtualClassTemplate()
{

}

}}}}//end namespace


